# Workflows Name
name: Generate Build

# Trigger
on:
  # Manual Trigger WorkFlows
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Enter the Branch from which you want to build'
        required: true

# Jobs  
jobs:

  # Job - 1 CheckOut the Code 
  checkout-code:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the code
          uses: actions/checkout@v4.1.0
          with:
            ref: ${{github.event.inputs.branch}}
  
        - name: Set up JDK 17
          uses: actions/setup-java@v3.13.0
          with:
            java-version: 17
            distribution: 'adopt'

  
  # Job - 2 Generate Debug Build 
  generate-debug-build:
     needs: checkout-code
     runs-on: ubuntu-latest
     steps:
       - name: Generate Debug Build
         run: |
           chmod +x ./gradlew
           ./gradlew bundleDebug
           

  # Job - 3 Upload Debug Build
  upload-debug-build:
     needs: generate-debug-build
     runs-on: ubuntu-latest
     steps:
      - name: Uploading Debug Bundle
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{github.event.inputs.branch}}-$(date +'%Y%m%d%H%M%S').aab
          path: app/build/outputs/bundle/debug/${{github.event.inputs.branch}}-$(date +'%Y%m%d%H%M%S').aab 
