# Workflows Name
name: Generate Build

# Trigger
on:
  # Manual Trigger Workflows
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Enter the Branch from which you want to build'
        required: true

# Jobs  
jobs:

  # Job - 1 Set Up JDK
  setup-jdk-code:
    runs-on: ubuntu-latest
    steps:
        - name: Set up JDK 17
          uses: actions/setup-java@v3.13.0
          with:
            java-version: 17
            distribution: 'adopt'

  
  # Job - 2 Generate Debug Build 
  generate-debug-build:
    needs: setup-jdk-code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code ${{ github.event.inputs.branch_name }} Branch
        uses: actions/checkout@v4.1.0
        with:
           ref: ${{ github.event.inputs.branch_name }}
  
      - name: Generate Debug Build ${{ github.event.inputs.branch_name }}
        run: |
          chmod +x ./gradlew
          ./gradlew bundleDebug

      - name: Uploading Debug ${{ github.event.inputs.branch_name }} Bundle
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ github.event.inputs.branch_name }}-$(date +'%Y%m%d%H%M%S').aab
          path: app/build/outputs/bundle/debug/${{ github.event.inputs.branch_name }}-$(date +'%Y%m%d%H%M%S').aab
