name: Generate Build

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Enter the Branch from which you want to build'
        required: true
  
jobs:

  build:
     runs-on: ubuntu-latest
    
     steps:
      - name: Checkout the code to a specific branch
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.inputs.branch }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt' # You can use a different distribution if needed

      - name: Build Debug APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

