name: Generate Build

on:
  workflow_dispatch:
  
jobs:

  build:
     runs-on: ubuntu-latest
    
     steps:
      - name: Fetch Branch Name
        id: fetch-branch
        run: echo "::set-output name=branch::${{ github.ref }}"
 
      - name: Checkout the code
        uses: actions/checkout@v4.1.0
        with:
          ref: ${{github.ref}}

       
      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Generate Debug Build
        run: |
           chmod +x ./gradlew
           ./gradlew bundleDebug

      - name: Uploading Debug Bundle
        uses: actions/upload-artifact@v3.1.3
        with:
          name: debug-bundle
          path: app/build/outputs/bundle/debug/app-debug.aab 

