name: Generate Build

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Enter the Branch from which you want to build'
        required: true
  
jobs:

  build:
     runs-on: ubuntu-latest
    
     steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.0
        with:
          ref: ${{github.event.inputs.branch }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Generate Debug Build
        run: |
           chmod +x ./gradlew
           ./gradlew bundleDebug

      - name: Uploading Debug Bundle
        uses: actions/upload-artifact@v3.1.3
        with:
          name: debug-bundle
          path: app/build/outputs/bundle/debug/app-debug.aab 

