name: Generate QA Build

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Enter the Branch from which you want to build'
        required: true

jobs:
  generate-qa-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.0
        with:
          ref: ${{ github.event.inputs.branch_name }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Generate Debug Build
        run: |
          chmod +x ./gradlew
          ./gradlew bundleDebug

      - name: Upload Debug Bundle
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ github.event.inputs.branch_name }}.aab
          path: app/build/outputs/bundle/debug/app-debug.aab

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: firebase login:ci --no-localhost --token "${{ secrets.RAHUL_FIREBASE_TOKEN }}"

      - name: Distribute App
        run: |
          firebase appdistribution:distribute app/build/outputs/apk/release/app-release-unsigned.apk \
          --app ${{ secrets.FIREBASE_APP_ID }} \
          --groups internal-testers

      - name: Get Distribution Link
        run: |
          distribution_link=$(firebase appdistribution:distributions:list --app ${{ secrets.FIREBASE_APP_ID }} --json | jq -r '.[0].downloadUrl')
          echo "Distribution Link: $distribution_link"
