name: Generate Build

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Enter the Branch from which you want to build'
        required: true
  
jobs:

  build:
     runs-on: ubuntu-latest
    
     steps:
      - name: Checkout the code to a specific branch
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.inputs.branch }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Generate Debug Build
        run: |
           chmod +x ./gradlew
           ./gradlew bundleDebug

      - name: Uploading Debug Bundle
        uses: actions/upload-artifact@v2
        with:
          name: debug-bundle
          path: app/build/outputs/bundle/debug/app-debug.aab
